name: mcat_package
description: "A new Flutter package project."
version: 0.0.1
homepage: "https://www.healthtech.dtu.dk/"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1 
  flutter_tts: ^3.8.3
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.8
  collection: ^1.17.0
  async: ^2.11.0
  http: ^1.1.0
  intl: ^0.18.0
  shared_preferences: ^2.1.1
  package_info_plus: ^4.0.0
  device_info_plus: ^9.0.0
  logger: ^1.2.2
  uuid: ^4.3.0
  csv: ^5.0.0
  archive: ^3.3.7
  dio: ^5.1.2
  retry: ^3.1.0
  animate_do: ^3.3.4 


  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  connectivity_plus: ^6.0.3
  path_provider: ^2.1.2
  google_fonts: ^6.3.2
  speech_to_text: ^7.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
flutter:
  uses-material-design: true